### ISSUE TITLE
need package it into a local game (not an online game on a web page)

### ISSUE THREAD

**Issue by Illyrix** [avgjs/avg-core#31]
I would like to play a gal game on my disk rather than online because it takes long time to load resources. [Electron](https://electron.atom.io/) can help us to package it into an cross-platform application. Saves can be store on disk instead of in 'local storage'. Also it can protect source code partly.
Could create a new project integrate Electron into it?

**Comment by Icemic** [comment]
It's easy to wrap it with electron, just wrap it. :)
And to save archives on the disk instead of local storage, you must implement your own storage plugin in place of https://github.com/avgjs/avg-core/blob/dev/src/plugins/localStorage.js, which listens several `signals` ralated to storage. Load your plugin at https://github.com/avgjs/template/blob/master/src/entry.jsx#L23.

**Comment by Icemic** [comment]
Seems no update for a long time, i'll close it while you can reopen it if needed.
